repos:
  - repo: local
    hooks:
      - id: gfmd
        name: gfm-diagrams
        description: "GFM Diagrams"
        entry: python src/markdown_process
        language: python
        language_version: python3
        require_serial: true
        types: [file]
        files: ".*\\.md"

